project 'ZHAddressTextFiled Example.xcodeproj'
source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'ZHAddressTextFiled' do
  pod "Masonry"
end

